# 网站的基本信息
site:
  tab: Southcatsm 
  title: scsm 
  description: southcatsm的个人网站 
  language: zh 
  favicon: /favicon.ico 
  theme: # 更多主题 https://daisyui.com/docs/themes/
    light: winter 
    dark: dracula 
    code: github-dark
  date_format: MMM DD YYYY
  menu:
    - id: home 
      text: 主页 
      href: /
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: 关于
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: 博客
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: 所有博客
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: tech
          text: 技术型博客
          href: /blog/category/tech
          svg: "material-symbols:deployed-code-outline"
          target: _self
        - id: life
          text: 生活型博客
          href: /blog/category/life
          svg: "material-symbols:earthquake-rounded"
          target: _self
    - id: project
      text: 作品
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: 朋友
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: 联系
      href: "mailto:contact.archie26@qq.com"
      target: _blank 
      svg: "material-symbols:attach-email-outline-rounded"

user:
  name: Southcatsm 
  site: "https://southcat.cc" 
  avatar: /profile.png 
  sidebar: 
    social:
      - href: "https://afdian.com/a/saroprock" #
        ariaLabel: Support my work 
        title: 赞助一手 
        svg: "ri:cup-line"
      - href: "https://github.com/southsatsm"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/635978552"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/lmarmi97"
        ariaLabel: X(twitter)
        title: X(原小蓝鸟)
        svg: "ri:twitter-line"
  footer:
    social:
      - href: "https://afdian.com/a/saroprock"
        ariaLabel: Support my work 
        title: Support my work
        svg: "ri:cup-line"
      - href: "https://github.com/southcatsm"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"
      - href: "https://space.bilibili.com/635978552"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"
      - href: "https://x.com/lmarmi97"
        ariaLabel: X(twitter)
        title: X(原小蓝鸟)
        svg: "ri:twitter-line"
